"""Inspect runtime state and coordinate explicit, serialized bootstrap work."""

import fcntl
import json
import os
import shlex
import stat
from contextlib import contextmanager
from pathlib import Path

from .adapters import ADAPTERS
from .errors import BootstrapError
from .paths import read_json_object, root_path, writable_directory


def select(manifest, only):
    """Resolve a selection in registry order, which installs requirements first.

    Without --only, every available default ecosystem is selected. An explicit
    selection must be available here and include what each member requires;
    it is never widened silently.
    """
    platform = manifest["platform"]
    if not only:
        return [
            language
            for language, adapter in ADAPTERS.items()
            if adapter.default_selected
            and adapter.describe(manifest)["available"]
        ]
    for language in only:
        adapter = ADAPTERS[language]
        if not adapter.declared(manifest):
            raise BootstrapError(
                "Selected native toolchain is absent from the baseline"
            )
        if platform not in adapter.platforms:
            raise BootstrapError(f"{language} is unavailable on {platform}")
        missing = [name for name in adapter.requires if name not in only]
        if missing:
            raise BootstrapError(
                f"{language} requires {', '.join(missing)}; select "
                + " ".join(f"--only {name}" for name in missing)
                + " as well"
            )
    return [language for language in ADAPTERS if language in only]


class Bootstrap:
    """The selected ecosystem adapters behind one explicit interface."""

    def __init__(self, manifest, only, accepted=()):
        self.data = manifest
        self.only = select(manifest, only)
        self.accepted = set(accepted)
        home = Path.home()
        # Existing hosts keep their lock and caches under these names.
        self.cache = (
            root_path("XDG_CACHE_HOME", home / ".cache") / "devrestore"
        )
        self.state = (
            root_path("XDG_STATE_HOME", home / ".local/state") / "devrestore"
        )
        self.adapters = {
            language: ADAPTERS[language](self) for language in self.only
        }

    @property
    def backend(self):
        return self.data["backend"]

    def adapter(self, language):
        return self.adapters[language]

    def catalog(self):
        """Every adapter's selection metadata, whether selected or not."""
        return [
            dict(adapter.describe(self.data), selected=language in self.only)
            for language, adapter in ADAPTERS.items()
        ]

    def require_consents(self):
        """Refuse an apply until every selected adapter's terms are accepted."""
        missing = sorted(
            {
                consent
                for adapter in self.adapters.values()
                for consent in adapter.consents
            }
            - self.accepted
        )
        if missing:
            raise BootstrapError(
                "The selection requires accepting "
                + ", ".join(missing)
                + "; review them, then rerun with "
                + " ".join(f"--accept {name}" for name in missing)
            )

    def manager(self, language):
        return self.adapter(language).manager()

    # Installation journal ----------------------------------------------------

    @property
    def journal_path(self):
        return self.state / "installing.json"

    def interrupted(self):
        """Prefixes an apply began creating and never finished.

        Only these may be removed automatically: everything else under a
        manager root may be the user's.
        """
        if not self.journal_path.is_file():
            return frozenset()
        prefixes = read_json_object(self.journal_path).get("prefixes")
        if not isinstance(prefixes, list) or not all(
            isinstance(prefix, str) for prefix in prefixes
        ):
            raise BootstrapError(
                f"Inspect the installation journal: {self.journal_path}"
            )
        return frozenset(prefixes)

    def journal(self, prefix, *, started):
        """Record or clear a prefix around its installation, atomically."""
        prefixes = set(self.interrupted())
        if started:
            prefixes.add(str(prefix))
        else:
            prefixes.discard(str(prefix))
        temporary = self.journal_path.with_suffix(".tmp")
        temporary.write_text(json.dumps({"prefixes": sorted(prefixes)}))
        os.replace(temporary, self.journal_path)

    def arguments(self, operation, **bindings):
        """Bind runtime paths to literal argv generated by Nix, never shell text."""
        return [
            token.format_map(bindings)
            for token in self.data["policy"]["commands"][operation]
        ]

    def environment(self):
        """Every selected manager root, as exported to child shells."""
        environment = {}
        for adapter in self.adapters.values():
            environment.update(adapter.environment())
        return environment

    def plan(self):
        """Inspect paths only. Present means installed, not yet validated."""
        return [
            row for adapter in self.adapters.values() for row in adapter.plan()
        ]

    def nix_runtime(self, row):
        """Bind a row to the exact nixpkgs runtime, never a nearby release."""
        runtime = self.data.get("nixRuntimes", {}).get(
            f"{row['language']}-{row['version']}", {}
        )
        if (
            runtime.get("version") == row["version"]
            and Path(runtime.get("path", "")).is_file()
        ):
            row.update(
                state="present",
                path=runtime["path"],
                owner="nixpkgs",
                isolated=runtime.get("isolated", True),
            )
        else:
            row.update(
                state="blocked",
                reason="No exact qualified nixpkgs runtime in this baseline",
            )

    def observed_state(self):
        """Report global selectors and additional versions without evaluating them."""
        return {
            "globalSelections": {
                language: adapter.selection()
                for language, adapter in self.adapters.items()
            },
            "installed": {
                language: adapter.installed()
                for language, adapter in self.adapters.items()
            },
        }

    def verify(self, row, *, exact=True):
        return self.adapter(row["language"]).verify(row, exact=exact)

    def qualify(self, rows, *, exact):
        """Verify present rows in place: ok, or conflict with the reason."""
        for row in rows:
            if row["state"] != "present":
                continue
            adapter = self.adapter(row["language"])
            try:
                identity = adapter.verify(row, exact=exact)
                if not exact:
                    row["actualVersion"] = identity
                row["state"] = "ok"
            except BootstrapError as error:
                row.update(state="conflict", reason=str(error))
                remedy = adapter.remediation(row)
                if remedy:
                    row["remediation"] = shlex.join(remedy)
        return rows

    @contextmanager
    def locked(self):
        """Serialize runtime, prerequisite and initial-selection mutations."""
        if os.geteuid() == 0:
            raise BootstrapError(
                "Run bootstrap as the owning account, never as root"
            )
        # Validate existing destinations before native installers or package
        # managers can write. Do not pre-create installer-owned directories.
        for adapter in self.adapters.values():
            for path in adapter.mutable_directories():
                writable_directory(path, create=False)
        writable_directory(self.cache, create=False)
        writable_directory(self.state)
        descriptor = os.open(
            self.state / "apply.lock",
            os.O_CREAT | os.O_RDWR | os.O_NOFOLLOW,
            0o600,
        )
        with os.fdopen(descriptor, "a") as lock:
            info = os.fstat(lock.fileno())
            if (
                not stat.S_ISREG(info.st_mode)
                or info.st_uid != os.geteuid()
                or info.st_mode & 0o022
            ):
                raise BootstrapError(
                    "Recovery lock must be a private regular file"
                )
            try:
                fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            except BlockingIOError as error:
                raise BootstrapError(
                    "Another recovery process is running"
                ) from error
            yield

    def apply(self, rows, *, lock_held=False, evolved=False):
        """Preflight every selected runtime; serialize only explicit mutations."""
        if not lock_held:
            self.require_consents()
            with self.locked():
                return self.apply(rows, lock_held=True, evolved=evolved)
        if any(row["state"] in ("blocked", "conflict") for row in rows):
            raise BootstrapError(
                "Recovery is blocked; inspect the plan before installing"
            )
        # A record whose prefix no longer exists vouches for nothing; drop it
        # before a later partial directory there could be mistaken for ours.
        for prefix in self.interrupted():
            if not os.path.lexists(prefix):
                self.journal(prefix, started=False)
        for row in rows:
            if row["state"] == "present":
                self.verify(row, exact=not evolved)
        missing = [row for row in rows if row["state"] == "missing"]
        if not missing:
            return
        for adapter in self.adapters.values():
            selected = [
                row for row in missing if row["language"] == adapter.language
            ]
            if selected:
                adapter.preflight(selected)
        # Reinspect after acquiring the lock; ordinary manager invocations
        # do not participate, so each adapter also guards its target.
        fresh = self.plan()
        if any(row["state"] in ("blocked", "conflict") for row in fresh):
            raise BootstrapError("State changed since planning")
        for row in fresh:
            if row["state"] == "missing":
                adapter = self.adapter(row["language"])
                prefix = adapter.owned_prefix(row)
                if row.get("interrupted"):
                    adapter.discard(prefix)
                # Journal a prefix before it exists, so an interruption at
                # any point leaves it recognizable as ours.
                if prefix is not None:
                    self.journal(prefix, started=True)
                adapter.install(row)
                adapter.verify(row)
                if prefix is not None:
                    self.journal(prefix, started=False)
