-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua

-- DAP: after all plugins are ready, map the LCS.Data symlink for codelldb and
-- add fallback launch/attach configs for C and C++ when none exist yet.
-- .vscode/launch.json needs no loading here: nvim-dap's "dap.launch.json"
-- provider reads it on demand every time a session starts (:help dap-providers).
vim.api.nvim_create_autocmd("User", {
  pattern = "LazyDone",
  once = true,
  callback = function()
    local ok_dap, dap = pcall(require, "dap")
    if not ok_dap then return end

    -- /Users/lcs-dev/LCS.Data is a symlink -> /Volumes/LCS.Data.
    -- The compiler embeds the symlink path in the debug info, but Neovim opens
    -- files via the real mount point. sourceMap tells codelldb to translate.
    local source_map = { ["/Users/lcs-dev/LCS.Data"] = "/Volumes/LCS.Data" }

    -- Add the sourceMap when a session starts, so it reaches every codelldb
    -- config: launch.json entries, which never enter dap.configurations, and
    -- the ones auto-generated by mason-nvim-dap. The copy keeps the stored
    -- configurations unchanged.
    dap.listeners.on_config["user.codelldb-source-map"] = function(config)
      if config.type ~= "codelldb" or config.sourceMap then return config end
      local mapped = vim.deepcopy(config)
      mapped.sourceMap = source_map
      return mapped
    end

    -- Fallback configs: used only when no launch.json exists and mason-nvim-dap
    -- has not auto-generated configurations for these filetypes.
    for _, ft in ipairs({ "c", "cpp" }) do
      if not dap.configurations[ft] or #dap.configurations[ft] == 0 then
        dap.configurations[ft] = {
          {
            name        = "Launch (codelldb)",
            type        = "codelldb",
            request     = "launch",
            program     = function()
              return vim.fn.input("Executable: ", vim.fn.getcwd() .. "/", "file")
            end,
            cwd         = "${workspaceFolder}",
            stopOnEntry = false,
            terminal    = "integrated",
            sourceMap   = source_map,
          },
          {
            name    = "Attach to process (codelldb)",
            type    = "codelldb",
            request = "attach",
            pid     = require("dap.utils").pick_process,
            cwd     = "${workspaceFolder}",
          },
        }
      end
    end
  end,
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = "markdown",
  callback = function()
    vim.opt_local.spell = true
    vim.opt_local.spelllang = "it,en"
  end,
})

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "tex", "plaintex" },
  callback = function()
    vim.opt_local.conceallevel = 2
  end,
})
