#!/usr/bin/env sh

# Description: Toggles executable mode for selection
#
# Dependencies: chmod
#
# Note: Works _only_ with selection (nnn can toggle the mode for the hovered file)
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

selection=${NNN_SEL:-${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.selection}

if [ -s "$selection" ]; then
    # The fixed child program receives filenames only through its argument.
    # shellcheck disable=SC2016
    xargs -0 -I {} sh -c 'if [ -x "$1" ]; then chmod -x -- "$1"; else chmod +x -- "$1"; fi' nnn-togglex {} < "$selection"

    # Clear selection
    if [ -p "$NNN_PIPE" ]; then
        printf "-" > "$NNN_PIPE"
    fi
fi
